
server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel dashboard地址
        port: 8719
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
service-url:
  user-service: http://user-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
